---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: rancher/dapper:v0.5.4
    commands:
    - dapper test
    volumes:
    - name: docker
      path: /var/run/docker.sock
    when:
      branch:
      - master
      event:
      - push
      - pull_request
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
